name: Continuous Integration

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: read

jobs:
  maven-build-lifecycle:
    runs-on: ubuntu-latest
    name: Maven Verify

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run maven build lifecycle
        run: mvn -B verify